INSERT INTO USERS VALUES('omoulin','OLIVIER','MOULIN','LOCAL','NO','omoulin@test.net',';cqfd567');


INSERT INTO PROJECT VALUES('PRJ00001','TEST PRJ 1','','NONE','NONE','omoulin');
INSERT INTO PROJECT VALUES('PRJ00002','TEST PRJ 2','','NONE','NONE','omoulin');
INSERT INTO PROJECT VALUES('PRJ00003','TEST PRJ 3','','NONE','NONE','omoulin');
INSERT INTO PROJECT VALUES('PRJ00004','TEST PRJ 4','','NONE','NONE','omoulin');
INSERT INTO PROJECT VALUES('PRJ00005','TEST PRJ 5','','NONE','NONE','omoulin');

INSERT INTO USERS VALUES('test','test','test','LOCAL','NO','test.test@stryker.com','test');


INSERT INTO PROJECT VALUES('PRJ00001','TEST PRJ 11','','NONE','NONE','test');
INSERT INTO PROJECT VALUES('PRJ00002','TEST PRJ 12','','NONE','NONE','test');
INSERT INTO PROJECT VALUES('PRJ00003','TEST PRJ 13','','NONE','NONE','test');
INSERT INTO PROJECT VALUES('PRJ00004','TEST PRJ 14','','NONE','NONE','test');
INSERT INTO PROJECT VALUES('PRJ00005','TEST PRJ 15','','NONE','NONE','test');